server.port=${SERVER_PORT:8004}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017}
spring.data.mongodb.database=ridelink_payments
spring.data.mongodb.auto-index-creation=true
springdoc.swagger-ui.path=/swagger-ui.html
spring.application.name=fare-payment-service
security.jwt.secret=${RIDE_LINK_JWT_SECRET:development-secret-change-before-use}
services.ride-url=${RIDE_URL:http://127.0.0.1:8003}
