spring.application.name=driver-vehicle-service

# Server
server.port=8082

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/ridelink_driver_vehicle_db

# Application
spring.mvc.problemdetails.enabled=true
