spring.application.name=ride-management-service

# Server
server.port=8083

# MongoDB
spring.mongodb.uri=mongodb://localhost:27017/ridelink_ride_management_db

# Application
spring.mvc.problemdetails.enabled=true

# Microservices
driver.service.url=http://localhost:8082
fare.service.url=http://localhost:8084