package lk.ridelink.fare;
import lk.ridelink.common.*;import io.swagger.v3.oas.annotations.security.SecurityRequirement;import jakarta.servlet.http.HttpServletRequest;import org.springframework.beans.factory.annotation.Value;import org.springframework.http.HttpStatus;import org.springframework.data.domain.Sort;import org.springframework.data.mongodb.core.MongoTemplate;import org.springframework.data.mongodb.core.index.Index;import org.springframework.data.mongodb.core.query.Criteria;import org.springframework.data.mongodb.core.query.Query;import org.springframework.context.event.EventListener;import org.springframework.boot.context.event.ApplicationReadyEvent;import org.bson.Document;import org.springframework.web.bind.annotation.*;import org.springframework.web.server.ResponseStatusException;import java.math.BigDecimal;import java.math.RoundingMode;import java.util.*;
@RestController public class FareController {
 private static final BigDecimal BASE=new BigDecimal("3.00"),RATE=new BigDecimal("2.00");private final MongoTemplate db;private final String secret,rideUrl;
 public FareController(MongoTemplate db,@Value("${security.jwt.secret}")String secret,@Value("${services.ride-url}")String rideUrl){this.db=db;this.secret=secret;this.rideUrl=rideUrl;}
 @EventListener(ApplicationReadyEvent.class) public void indexes(){db.indexOps("payments").ensureIndex(new Index().on("ride_id",Sort.Direction.ASC).unique());}
 public record Estimate(Double distance_km){}public record RideId(String ride_id){}public record Payment(String payment_id,String ride_id,BigDecimal amount,String currency,String status,String receipt){}
 @PostMapping("/fares/estimate") @SecurityRequirement(name="bearerAuth") public Map<String,Object> estimate(HttpServletRequest req,@RequestBody Estimate b){Auth.require(req,secret,"passenger","driver","admin");if(b.distance_km()==null||!Double.isFinite(b.distance_km())||b.distance_km()<=0||b.distance_km()>500)throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"distance_km must be greater than 0 and at most 500");BigDecimal distance=BigDecimal.valueOf(b.distance_km());BigDecimal amount=BASE.add(RATE.multiply(distance)).setScale(2,RoundingMode.HALF_UP);return Map.of("distance_km",b.distance_km(),"estimated_fare",amount,"currency","LKR","rule","LKR 3.00 base + LKR 2.00 per simulated kilometre");}
 @PostMapping("/payments") @ResponseStatus(HttpStatus.CREATED) @SecurityRequirement(name="bearerAuth") public Payment charge(HttpServletRequest req,@RequestBody RideId b){var caller=Auth.require(req,secret,"passenger");if(b.ride_id()==null||b.ride_id().isBlank())throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"ride_id required");String bearer=req.getHeader("Authorization").substring(7);var ride=Remote.post(rideUrl+"/rides/get",Map.of("ride_id",b.ride_id()),bearer);if(!caller.subject().equals(String.valueOf(ride.get("passenger_id"))))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Ride belongs to another passenger");if(!"completed".equals(ride.get("status")))throw new ResponseStatusException(HttpStatus.CONFLICT,"Only completed rides can be paid");BigDecimal amount=new BigDecimal(String.valueOf(ride.get("fare"))).setScale(2,RoundingMode.HALF_UP);String id=UUID.randomUUID().toString();db.insert(new Document("id",id).append("ride_id",b.ride_id()).append("passenger_id",caller.subject()).append("amount",amount).append("currency","LKR").append("status","succeeded").append("created_at",new Date()),"payments");return new Payment(id,b.ride_id(),amount,"LKR","succeeded","RL-"+id.substring(0,8));}
 @PostMapping("/payments/receipt") @SecurityRequirement(name="bearerAuth") public Map<String,Object> receipt(HttpServletRequest req,@RequestBody Map<String,String> b){var caller=Auth.require(req,secret);var row=db.findOne(Query.query(Criteria.where("id").is(b.get("payment_id"))),Document.class,"payments");if(row==null)throw new ResponseStatusException(HttpStatus.NOT_FOUND,"Payment not found");if(!"admin".equals(caller.role())&&!caller.subject().equals(row.getString("passenger_id")))throw new ResponseStatusException(HttpStatus.FORBIDDEN,"Receipt belongs to another passenger");row.put("receipt","RL-"+row.getString("id").substring(0,8));return row;}
}
